version: '3.9'

services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - '3000:3000'
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    environment:
    - REDIS_PASSWORD=redisPassword

  employee_db:
    image: postgres:12.0-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: employee
    volumes:
      - employee:/var/lib/postgresql/data

  employee:
    build: 
      context: ./employee
      dockerfile: ../Dockerfile
    volumes:
      - ./employee:/var/www/html
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redisPassword
      DB_HOST: employee_db
      DB_PORT: 5432
      DB_DATABASE: employee
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - redis
      - employee_db
    ports:
      - "8004:8000"

  administrator_db:
    image: postgres:12.0-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: administrato
    volumes:
      - administrator:/var/lib/postgresql/data

  administrator:
    build: 
      context: ./administrator
      dockerfile: ../Dockerfile
    volumes:
      - ./administrator:/var/www/html
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redisPassword
      DB_HOST: administrator_db
      DB_PORT: 5433
      DB_DATABASE: administrator
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - "8005:8000"
    depends_on:
      - redis
      - administrator_db

  restaurant_db:
    image: postgres:12.0-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant
    volumes:
      - restaurant:/var/lib/postgresql/data

  restaurant:
    build: 
      context: ./restaurant
      dockerfile: ../Dockerfile
    volumes:
      - ./restaurant:/var/www/html
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redisPassword
      DB_HOST: restaurant_db
      DB_PORT: 5432
      DB_DATABASE: restaurant
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - "8006:8000"
    depends_on:
      - redis
      - restaurant_db
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8080:8081"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
volumes:
  employee:
  restaurant:
  administrator:
  redis_data: