# Base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the Next.js project to the container
COPY . /app

# Install dependencies
RUN npm install

# Set the environment variables
ENV NODE_ENV=development

# Expose port 3000 and start the development server
EXPOSE 3000
CMD ["npm", "run", "dev"]
